/** Pantry Modernism: the home page puts food and service clarity side by side on a composed workbench. */
import { ArrowDownRight, ArrowUpRight, CalendarDays, ChevronRight, ClipboardCheck, CreditCard, PackageCheck } from "lucide-react";
import { Link } from "wouter";
import { bakeryItems } from "@/lib/bakery-data";
import { useOrder } from "@/contexts/OrderContext";

export default function Home() {
  const { addItem } = useOrder();
  return <>
    <section className="hero"><div className="hero-copy"><div className="hero-kicker"><span className="citrus-dot" /> Maplewood, New Jersey <i>•</i> Wednesday–Saturday</div><h1>Small-batch cakes<br />for <em>big local moments.</em></h1><p>Custom cakes, everyday bakes, and a calmer way to place the order.</p><div className="hero-actions"><Link className="button button-primary" href="/custom-orders">Start a custom order <ChevronRight size={16} /></Link><Link className="text-link" href="/shop">See today’s counter <ArrowDownRight size={17} /></Link></div></div><div className="hero-image"><img src="/images/clementine-hero_cf591ab0.jpg" alt="A buttercream celebration cake topped with citrus" /><div className="hero-image-note"><span>01</span><p><b>This week’s feature</b><br />Citrus blossom cake</p></div></div><div className="hero-rail"><span>THE GOOD STUFF, MADE TO ORDER</span></div></section>
    <section className="operational-strip"><span>Two ways to order</span><p>Everyday bakes, ready when you are <i>→</i> Custom work, built around your date</p><Link href="/track-order">Track an order <ArrowUpRight size={15} /></Link></section>
    <section className="menu-highlights"><div className="section-heading"><div><span className="eyebrow">From the counter</span><h2>Good things, <em>today.</em></h2></div><Link className="text-link" href="/shop">All daily bakes <ArrowUpRight size={16} /></Link></div><div className="highlight-grid">{bakeryItems.slice(0, 3).map((item, index) => <article key={item.id} className={`highlight-card highlight-${index}`}><div className="highlight-art"><span>0{index + 1}</span><div className={`pastry pastry-${item.id}`}><i /><i /><i /></div></div><div><p>{item.category}</p><h3>{item.name}</h3><div className="highlight-order"><strong>${item.price.toFixed(2)}</strong><button onClick={() => addItem(item)}>Add to order <span>+</span></button></div></div></article>)}</div></section>
    <section className="custom-pitch"><div className="pitch-copy"><span className="eyebrow">Custom cake service</span><h2>The cake has a plan.<br /><em>Now, so do you.</em></h2><p>Our custom order form catches the size, flavors, design direction, and date details before a single message gets lost in the shuffle.</p><Link href="/custom-orders" className="button button-navy">Build your cake brief <ChevronRight size={16} /></Link></div><div className="pitch-process"><div className="recipe-tape">FROM “WHAT’S POSSIBLE?” TO “IT’S READY.”</div><div className="process-steps"><article><span>01</span><ClipboardCheck size={21} /><h3>Share the details</h3><p>Style, servings, flavors, and your inspiration—right in one request.</p></article><article><span>02</span><CalendarDays size={21} /><h3>Hold the date</h3><p>Open days only. Our capacity is visible before you choose.</p></article><article><span>03</span><CreditCard size={21} /><h3>Approve the quote</h3><p>Accept your quote and pay a 50% deposit to confirm.</p></article><article><span>04</span><PackageCheck size={21} /><h3>Pick up happy</h3><p>Track progress, then come collect the good part.</p></article></div></div></section>
    <section className="kitchen-band"><div className="kitchen-visual"><div className="baker-abstract"><span /><span /><span /></div><div className="kitchen-stamp"><span className="citrus-mark large"><i /><i /><i /><i /><i /><i /><i /><i /></span><p>Carefully<br />made here.</p></div></div><div className="kitchen-copy"><span className="eyebrow">A local kitchen</span><h2>Built for the part<br />of the day <em>people remember.</em></h2><p>We keep our menu short, our windows clear, and our buttercream soft. The result is a bakery that feels personal because it is.</p><Link href="/about" className="text-link">Meet our kitchen <ArrowUpRight size={16} /></Link></div></section>
    <section className="home-signals"><div><span className="citrus-dot" /><h3>Custom, not complicated.</h3><p>One considered request form replaces the long, uncertain message thread.</p></div><div><span className="citrus-dot" /><h3>Capacity you can see.</h3><p>Full dates lock automatically, so we only promise what we can make well.</p></div><div><span className="citrus-dot" /><h3>Clear from quote to cake.</h3><p>Deposits and balances are visible before the final pickup moment.</p></div></section>
  </>;
}
